### ISSUE TITLE
11/23 진도점검

### ISSUE THREAD

**Issue by blackgetter** [kocharmPrj/0kcal#11]
UI (View Class)

- 데이터 받아올 경우 업데이트 하는 기능 추가 중
- 오늘의 식단, 저장하는 것 -> Gallery View로 추가
- Food Info와 Menu Info Design 필요

Controller Class

GUI Control
- UI와 기능 Merge

Model
- UI git 업로드 후 Model단 추가하겠음

AI modeling
- Text recognition과 Object Detection 둘다 Accuracy 낮은 상황
- 먼저 DB와 연계할 수 있도록 Class화 요청

**Comment by 0419jinho** [comment]
AI modeling part
1. 낮은 accuracy 알고리즘 개선을 통해 해결
2. Class화 해서 PR 생성
