### ISSUE TITLE
DB 음식 리스트

### ISSUE THREAD

**Issue by Eun04** [kocharmPrj/0kcal#35]
procedure
식품명 | 연도 | 1회제공량 | 에너지(㎉) | 단백질(g) | 지방(g) | 탄수화물(g) | 총당류(g) | 나트륨(㎎) | 콜레스테롤(㎎) | 총 포화 지방산(g) | 성분표출처 | 발행기관

food
햄버그스테이크 | 2019 | 200 | 457.697 | 26.959 | 29.646 | 20.761 | 5.334 | 950.22 | 70.276 | 9.409 | 식약처('13) 제2권 | 식품의약품안전처
오일소스스파게티 | 2019 | 400 | 646.736 | 19.555 | 23.426 | 89.42 | 1.411 | 1124.332 | 31.621 | 3.892 | 식약처('13) 제2권 | 식품의약품안전처
크림소스스파게티 | 2019 | 400 | 837.57 | 21.794 | 50.594 | 73.763 | 9.173 | 1030.21 | 126.578 | 25.665 | 식약처('13) 제2권 | 식품의약품안전처
토마토소스스파게티 | 2019 | 500 | 642.583 | 24.349 | 19.152 | 93.204 | 15.598 | 1508.634 | 49.168 | 5.437 | 식약처('13) 제2권 | 식품의약품안전처
불고기피자 | 2019 | 200 | 505 | 27.4 | 16.7 | 61.2 | 9.2 | 916.87 | 45.7 | 9.3 | 식약처('17) 제5권 | 식품의약품안전처
치즈피자 | 2019 | 200 | 553 | 31.4 | 15.8 | 71.2 | 6.8 | 949.96 | 48.04 | 11.5 | 식약처('17) 제5권 | 식품의약품안전처
페퍼로니피자 | 2019 | 200 | 532 | 29.4 | 14.8 | 70.3 | 7.5 | 945.22 | 41.73 | 10.9 | 식약처('17) 제5권 | 식품의약품안전처
포테이토피자 | 2019 | 250 | 628 | 28 | 25.5 | 71.6 | 8.5 | 999.93 | 48.95 | 10.3 | 식약처('17) 제5권 | 식품의약품안전처

**Comment by 0419jinho** [comment]
Cola(355ml) – 152kcal, 탄수화물 38.3g, 단백질 0g, 지방 0g, 당류 38.34g, 나트륨 11.36mg
americano(스타벅스)(355ml) – 10kcal, 탄수화물 2.00g, 단백질 1g, 지방 0g, 당류 0g, 나트륨 5mg 
fanta orange(355ml) – 68kcal, 탄수화물 17.00g, 단백질 0.00g, 지방 0.00g, 당류 17.0g, 나트륨 11mg

**Comment by rojong00** [comment]
![Screenshot from 2023-11-26 16-36-21](https://github.com/kocharmPrj/0kcal/assets/49092381/57bda911-584c-4bd5-8fa2-df36bbf39c97)

i made a db including them!
