### ISSUE TITLE
PyQt 1124

### ISSUE THREAD

**Issue by rojong00** [kocharmPrj/0kcal#37]
1. new model.py and revision of GUIctrl.py following updating of model.py
2. i add
 - file write function for Store btn in Ui_FoodDialog in model.py
 - foodInfoRequest function for communication DB. it will returns Dictionary type data in model.py. it needs string as arg1 for finding food name in DB.
   ( food_name, calorie, etc...)
3. i'm working
 - file load function in model.py
 4. i'll update my code following "combine_controller" on 11.26.Sat
    Just refer model.py
You can find All above things in 1122pyqt branch

**Comment by 0419jinho** [comment]
done
