### ISSUE TITLE
openvino enviroment Requirements.txt

### ISSUE THREAD

**Issue by Eun04** [kocharmPrj/0kcal#38]
numpy==1.26.2
opencv-python==4.8.1.78
openvino==2023.2.0
openvino-telemetry==2023.2.1

**Comment by 0419jinho** [comment]
opencv-python 설치 시 pyqt5 와 opencv-python 내부 qt 충돌 사항 발생
해결 방법 opencv-python lib 안에 있는 qt 폴더 삭제

**Comment by 0419jinho** [comment]
openvino==2023.1.0
openvino-dev==2023.1.0
