### ISSUE TITLE
11/25 진도상황 및 남은일

### ISSUE THREAD

**Issue by blackgetter** [kocharmPrj/0kcal#43]
현재 진도상황

- UI와 Object Detection 및 Text Classification 기능 merge 중
- Text Classification 인식률 개선
- Object Detection 인식률 개선

남은 일
- 식단 저장 및 로드 기능 업데이트
- 모델로부터 영양정보 및 메뉴정보 가져오기 기능 merge
- 메인브랜치 파일정리
- 통합 데모
- 갤러리 뷰 기능 업데이트
- 코드 리뷰
- 클래스다이어그램 및 시퀀스 다이어그램 수정
- 리팩토링
- pylint 사용하여 점수 높이기
- 발표자료 만들기

**Comment by 0419jinho** [comment]
Text Classification 인식률 개선 완료
- 메뉴판 제작
- 유사성 검사 과정 추가
