### ISSUE TITLE
Food detection menu list

### ISSUE THREAD

**Issue by Eun04** [kocharmPrj/0kcal#63]
식품명|제공량(g)|에너지(㎉)|단백질(g)|지방(g)|탄수화물(g)|총당류(g)|나트륨(㎎)

된장찌개|100|37.00|2.90g|0g|3.40g|0|505.00
미역국|100|323.00|9.4|0|63.2|0|6,516
조미김|5|23|1.02|1.51|1.45|0.01|200.55
시금치|50|1.87|2.23|1.68|0.05|68.12
게장|250|155.40|17.56|2.76|15.09|10.53|2,722.89
잡채|100|204|4.00|4.00|38.00|4.00|467.
갈비|100|270|24.83|15.41|0|0|79
밥|100|146|2.65|0.27|31.71|0.01|0
고등어구이|200|551.80|47.65|39.95|0.40|0.45|1,210
숙주나물|50|17.50|1.11|0.79|1.48|0.79|201.52

영어 이름 (순서대로)
soybean paste stew, seaweed soup, seaweed, spinach, marinated raw crabs, japchae, grilled short ribs, rice, grilled mackerel, seasoned mung bean sprouts

**Comment by 0419jinho** [comment]
![스크린샷 2023-11-26 19-56-01](https://github.com/kocharmPrj/0kcal/assets/142784142/dc7a2f2d-2571-4b11-9a0a-502e036ec94c)

**Comment by rojong00** [comment]
uploaded to db.
finished.

**Comment by rojong00** [comment]
![Screenshot from 2023-11-27 17-57-16](https://github.com/kocharmPrj/0kcal/assets/49092381/6238fdf8-0482-41ae-aa97-6d5ceef2f28a)
