### ISSUE TITLE
UI Design 

### ISSUE THREAD

**Issue by blackgetter** [kocharmPrj/0kcal#7]
1. 메인화면
![메인화면](https://github.com/kocharmPrj/0kcal/assets/16046747/c48bf90a-05ae-4a42-8e0e-e190577f9857)

2. 영양정보
![영양 정보](https://github.com/kocharmPrj/0kcal/assets/16046747/e4e12b86-d075-4011-92b4-c908f8121352)

3. 메뉴정보
![메뉴 정보](https://github.com/kocharmPrj/0kcal/assets/16046747/8fbb016a-3e43-44c5-bdbc-ca7c4af1cdf1)

4. 오늘의 식단
![오늘의 식단](https://github.com/kocharmPrj/0kcal/assets/16046747/fc525017-0b62-4d4a-90ef-554a956c5273)

5. 갤러리 조회
![갤러리 조회](https://github.com/kocharmPrj/0kcal/assets/16046747/25d72ddb-d146-45b3-ac33-a0293a30011b)

**Comment by 0419jinho** [comment]
Good  design!!

**Comment by jjooeun** [comment]
디자인 어딨는데요..?
왜 저만 안보이죠? ㅋㅋ

**Comment by 0419jinho** [comment]
디자인 없어졌어요

**Comment by blackgetter** [comment]
1120 15:32

수정사항 & 요청사항 feedback은 코멘트 남겨주세요~

**Comment by 0419jinho** [comment]
UI design 완료
